//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Saturn.ViewModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPSILab.SolarSystem.Saturn.ViewModel.Resources.AppResources-en", typeof(AppResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bureau.
        /// </summary>
        public static string LBL_BUREAU {
            get {
                return ResourceManager.GetString("LBL_BUREAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conferences.
        /// </summary>
        public static string LBL_CONFERENCES {
            get {
                return ResourceManager.GetString("LBL_CONFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string LBL_NEWS {
            get {
                return ResourceManager.GetString("LBL_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string LBL_PROJECTS {
            get {
                return ResourceManager.GetString("LBL_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows.
        /// </summary>
        public static string LBL_SALONS {
            get {
                return ResourceManager.GetString("LBL_SALONS", resourceCulture);
            }
        }
    }
}
