//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Saturn.WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Saturn.WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPSILab.
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to par {0} {1}, le.
        /// </summary>
        public static string FORMAT_AUTHOR {
            get {
                return ResourceManager.GetString("FORMAT_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {0:d} de {0:t} à {1:t}, {2}.
        /// </summary>
        public static string FORMAT_CONFERENCE {
            get {
                return ResourceManager.GetString("FORMAT_CONFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je vous invite à lire cet article:{4}{0}{4}{4}écrit par: {1} {2}{4}{4}{3}.
        /// </summary>
        public static string FORMAT_EMAIL_NEWS {
            get {
                return ResourceManager.GetString("FORMAT_EMAIL_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {0:g} au {1:g}, à {2}.
        /// </summary>
        public static string FORMAT_SALON {
            get {
                return ResourceManager.GetString("FORMAT_SALON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à propos.
        /// </summary>
        public static string LBL_ABOUT {
            get {
                return ResourceManager.GetString("LBL_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPSILab est une association étudiante qui promouvoit les produits et technologies Microsoft au sein des écoles du groupe EPSI. Ses activités se concentrent sur la formation des étudiants aux technologies Microsoft, à la réalisation de projets, à l&apos;organisation de conférences au sein de l&apos;école, à la participation au concours Imagine Cup et aux grands rendez-vous de Microsoft..
        /// </summary>
        public static string LBL_ASSOCIATION_INFORMATIONS {
            get {
                return ResourceManager.GetString("LBL_ASSOCIATION_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Développement par Jean-Baptiste Vigneron.
        /// </summary>
        public static string LBL_DEVELOPMENT_INFORMATIONS {
            get {
                return ResourceManager.GetString("LBL_DEVELOPMENT_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string LBL_EMAIL {
            get {
                return ResourceManager.GetString("LBL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to epsilab@outlook.com.
        /// </summary>
        public static string LBL_EMAIL_SUPPORT {
            get {
                return ResourceManager.GetString("LBL_EMAIL_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charger plus....
        /// </summary>
        public static string LBL_LOAD_MORE_ITEMS {
            get {
                return ResourceManager.GetString("LBL_LOAD_MORE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to épingler.
        /// </summary>
        public static string LBL_PIN {
            get {
                return ResourceManager.GetString("LBL_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rafraîchir.
        /// </summary>
        public static string LBL_REFRESH {
            get {
                return ResourceManager.GetString("LBL_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partager.
        /// </summary>
        public static string LBL_SHARE {
            get {
                return ResourceManager.GetString("LBL_SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sur le site.
        /// </summary>
        public static string LBL_WEBSITE {
            get {
                return ResourceManager.GetString("LBL_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez déjà épinglé cet élément..
        /// </summary>
        public static string MSG_ALREADY_PINNED {
            get {
                return ResourceManager.GetString("MSG_ALREADY_PINNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue. Veuillez réessayer ultérieurement..
        /// </summary>
        public static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ne parvenons pas à obtenir la liste d&apos;éléments pour l&apos;instant. Veuillez vérifier votre connexion Internet..
        /// </summary>
        public static string MSG_NO_NETWORK {
            get {
                return ResourceManager.GetString("MSG_NO_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de support pour l&apos;application EPSILab pour Windows Phone.
        /// </summary>
        public static string MSG_SUPPORT {
            get {
                return ResourceManager.GetString("MSG_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferences.
        /// </summary>
        public static string PAGE_CONFERENCES {
            get {
                return ResourceManager.GetString("PAGE_CONFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membres.
        /// </summary>
        public static string PAGE_MEMBRES {
            get {
                return ResourceManager.GetString("PAGE_MEMBRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualites.
        /// </summary>
        public static string PAGE_NEWS {
            get {
                return ResourceManager.GetString("PAGE_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salons.
        /// </summary>
        public static string PAGE_SALONS {
            get {
                return ResourceManager.GetString("PAGE_SALONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette tâche met à jour la tuile de l&apos;application EPSILab, en récupérant la dernière actualité du site web..
        /// </summary>
        public static string TASK_DESCRIPTION {
            get {
                return ResourceManager.GetString("TASK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.epsi.fr.
        /// </summary>
        public static string URL_EPSI {
            get {
                return ResourceManager.GetString("URL_EPSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/epsilab.
        /// </summary>
        public static string URL_FACEBOOK {
            get {
                return ResourceManager.GetString("URL_FACEBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.twitter.com/epsilab.
        /// </summary>
        public static string URL_TWITTER {
            get {
                return ResourceManager.GetString("URL_TWITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.epsilab.net/{0}-{1}-{2}.aspx.
        /// </summary>
        public static string WEBSITE_FORMAT {
            get {
                return ResourceManager.GetString("WEBSITE_FORMAT", resourceCulture);
            }
        }
    }
}
