//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Saturn.WindowsPhone8.TileFactory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPSILab.SolarSystem.Saturn.WindowsPhone8.TileFactory.Resources.LibResources", typeof(LibResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdLastConferenceSaved.
        /// </summary>
        internal static string ConferenceStorageKey {
            get {
                return ResourceManager.GetString("ConferenceStorageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochaine conf..
        /// </summary>
        internal static string NewConference {
            get {
                return ResourceManager.GetString("NewConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière news.
        /// </summary>
        internal static string NewNews {
            get {
                return ResourceManager.GetString("NewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochain salon.
        /// </summary>
        internal static string NewShow {
            get {
                return ResourceManager.GetString("NewShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdLastNewsSaved.
        /// </summary>
        internal static string NewsStorageKey {
            get {
                return ResourceManager.GetString("NewsStorageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdLastShowSaved.
        /// </summary>
        internal static string ShowStorageKey {
            get {
                return ResourceManager.GetString("ShowStorageKey", resourceCulture);
            }
        }
    }
}
